	soc_system u0 (
		.clk_clk                         (<connected-to-clk_clk>),                         //                 clk.clk
		.hps_0_f2h_axi_clock_clk         (<connected-to-hps_0_f2h_axi_clock_clk>),         // hps_0_f2h_axi_clock.clk
		.hps_0_f2h_axi_slave_awid        (<connected-to-hps_0_f2h_axi_slave_awid>),        // hps_0_f2h_axi_slave.awid
		.hps_0_f2h_axi_slave_awaddr      (<connected-to-hps_0_f2h_axi_slave_awaddr>),      //                    .awaddr
		.hps_0_f2h_axi_slave_awlen       (<connected-to-hps_0_f2h_axi_slave_awlen>),       //                    .awlen
		.hps_0_f2h_axi_slave_awsize      (<connected-to-hps_0_f2h_axi_slave_awsize>),      //                    .awsize
		.hps_0_f2h_axi_slave_awburst     (<connected-to-hps_0_f2h_axi_slave_awburst>),     //                    .awburst
		.hps_0_f2h_axi_slave_awlock      (<connected-to-hps_0_f2h_axi_slave_awlock>),      //                    .awlock
		.hps_0_f2h_axi_slave_awcache     (<connected-to-hps_0_f2h_axi_slave_awcache>),     //                    .awcache
		.hps_0_f2h_axi_slave_awprot      (<connected-to-hps_0_f2h_axi_slave_awprot>),      //                    .awprot
		.hps_0_f2h_axi_slave_awvalid     (<connected-to-hps_0_f2h_axi_slave_awvalid>),     //                    .awvalid
		.hps_0_f2h_axi_slave_awready     (<connected-to-hps_0_f2h_axi_slave_awready>),     //                    .awready
		.hps_0_f2h_axi_slave_awuser      (<connected-to-hps_0_f2h_axi_slave_awuser>),      //                    .awuser
		.hps_0_f2h_axi_slave_wid         (<connected-to-hps_0_f2h_axi_slave_wid>),         //                    .wid
		.hps_0_f2h_axi_slave_wdata       (<connected-to-hps_0_f2h_axi_slave_wdata>),       //                    .wdata
		.hps_0_f2h_axi_slave_wstrb       (<connected-to-hps_0_f2h_axi_slave_wstrb>),       //                    .wstrb
		.hps_0_f2h_axi_slave_wlast       (<connected-to-hps_0_f2h_axi_slave_wlast>),       //                    .wlast
		.hps_0_f2h_axi_slave_wvalid      (<connected-to-hps_0_f2h_axi_slave_wvalid>),      //                    .wvalid
		.hps_0_f2h_axi_slave_wready      (<connected-to-hps_0_f2h_axi_slave_wready>),      //                    .wready
		.hps_0_f2h_axi_slave_bid         (<connected-to-hps_0_f2h_axi_slave_bid>),         //                    .bid
		.hps_0_f2h_axi_slave_bresp       (<connected-to-hps_0_f2h_axi_slave_bresp>),       //                    .bresp
		.hps_0_f2h_axi_slave_bvalid      (<connected-to-hps_0_f2h_axi_slave_bvalid>),      //                    .bvalid
		.hps_0_f2h_axi_slave_bready      (<connected-to-hps_0_f2h_axi_slave_bready>),      //                    .bready
		.hps_0_f2h_axi_slave_arid        (<connected-to-hps_0_f2h_axi_slave_arid>),        //                    .arid
		.hps_0_f2h_axi_slave_araddr      (<connected-to-hps_0_f2h_axi_slave_araddr>),      //                    .araddr
		.hps_0_f2h_axi_slave_arlen       (<connected-to-hps_0_f2h_axi_slave_arlen>),       //                    .arlen
		.hps_0_f2h_axi_slave_arsize      (<connected-to-hps_0_f2h_axi_slave_arsize>),      //                    .arsize
		.hps_0_f2h_axi_slave_arburst     (<connected-to-hps_0_f2h_axi_slave_arburst>),     //                    .arburst
		.hps_0_f2h_axi_slave_arlock      (<connected-to-hps_0_f2h_axi_slave_arlock>),      //                    .arlock
		.hps_0_f2h_axi_slave_arcache     (<connected-to-hps_0_f2h_axi_slave_arcache>),     //                    .arcache
		.hps_0_f2h_axi_slave_arprot      (<connected-to-hps_0_f2h_axi_slave_arprot>),      //                    .arprot
		.hps_0_f2h_axi_slave_arvalid     (<connected-to-hps_0_f2h_axi_slave_arvalid>),     //                    .arvalid
		.hps_0_f2h_axi_slave_arready     (<connected-to-hps_0_f2h_axi_slave_arready>),     //                    .arready
		.hps_0_f2h_axi_slave_aruser      (<connected-to-hps_0_f2h_axi_slave_aruser>),      //                    .aruser
		.hps_0_f2h_axi_slave_rid         (<connected-to-hps_0_f2h_axi_slave_rid>),         //                    .rid
		.hps_0_f2h_axi_slave_rdata       (<connected-to-hps_0_f2h_axi_slave_rdata>),       //                    .rdata
		.hps_0_f2h_axi_slave_rresp       (<connected-to-hps_0_f2h_axi_slave_rresp>),       //                    .rresp
		.hps_0_f2h_axi_slave_rlast       (<connected-to-hps_0_f2h_axi_slave_rlast>),       //                    .rlast
		.hps_0_f2h_axi_slave_rvalid      (<connected-to-hps_0_f2h_axi_slave_rvalid>),      //                    .rvalid
		.hps_0_f2h_axi_slave_rready      (<connected-to-hps_0_f2h_axi_slave_rready>),      //                    .rready
		.hps_0_h2f_reset_reset_n         (<connected-to-hps_0_h2f_reset_reset_n>),         //     hps_0_h2f_reset.reset_n
		.hps_io_hps_io_emac1_inst_TX_CLK (<connected-to-hps_io_hps_io_emac1_inst_TX_CLK>), //              hps_io.hps_io_emac1_inst_TX_CLK
		.hps_io_hps_io_emac1_inst_TXD0   (<connected-to-hps_io_hps_io_emac1_inst_TXD0>),   //                    .hps_io_emac1_inst_TXD0
		.hps_io_hps_io_emac1_inst_TXD1   (<connected-to-hps_io_hps_io_emac1_inst_TXD1>),   //                    .hps_io_emac1_inst_TXD1
		.hps_io_hps_io_emac1_inst_TXD2   (<connected-to-hps_io_hps_io_emac1_inst_TXD2>),   //                    .hps_io_emac1_inst_TXD2
		.hps_io_hps_io_emac1_inst_TXD3   (<connected-to-hps_io_hps_io_emac1_inst_TXD3>),   //                    .hps_io_emac1_inst_TXD3
		.hps_io_hps_io_emac1_inst_RXD0   (<connected-to-hps_io_hps_io_emac1_inst_RXD0>),   //                    .hps_io_emac1_inst_RXD0
		.hps_io_hps_io_emac1_inst_MDIO   (<connected-to-hps_io_hps_io_emac1_inst_MDIO>),   //                    .hps_io_emac1_inst_MDIO
		.hps_io_hps_io_emac1_inst_MDC    (<connected-to-hps_io_hps_io_emac1_inst_MDC>),    //                    .hps_io_emac1_inst_MDC
		.hps_io_hps_io_emac1_inst_RX_CTL (<connected-to-hps_io_hps_io_emac1_inst_RX_CTL>), //                    .hps_io_emac1_inst_RX_CTL
		.hps_io_hps_io_emac1_inst_TX_CTL (<connected-to-hps_io_hps_io_emac1_inst_TX_CTL>), //                    .hps_io_emac1_inst_TX_CTL
		.hps_io_hps_io_emac1_inst_RX_CLK (<connected-to-hps_io_hps_io_emac1_inst_RX_CLK>), //                    .hps_io_emac1_inst_RX_CLK
		.hps_io_hps_io_emac1_inst_RXD1   (<connected-to-hps_io_hps_io_emac1_inst_RXD1>),   //                    .hps_io_emac1_inst_RXD1
		.hps_io_hps_io_emac1_inst_RXD2   (<connected-to-hps_io_hps_io_emac1_inst_RXD2>),   //                    .hps_io_emac1_inst_RXD2
		.hps_io_hps_io_emac1_inst_RXD3   (<connected-to-hps_io_hps_io_emac1_inst_RXD3>),   //                    .hps_io_emac1_inst_RXD3
		.hps_io_hps_io_sdio_inst_CMD     (<connected-to-hps_io_hps_io_sdio_inst_CMD>),     //                    .hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_D0      (<connected-to-hps_io_hps_io_sdio_inst_D0>),      //                    .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1      (<connected-to-hps_io_hps_io_sdio_inst_D1>),      //                    .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_CLK     (<connected-to-hps_io_hps_io_sdio_inst_CLK>),     //                    .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2      (<connected-to-hps_io_hps_io_sdio_inst_D2>),      //                    .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3      (<connected-to-hps_io_hps_io_sdio_inst_D3>),      //                    .hps_io_sdio_inst_D3
		.hps_io_hps_io_usb1_inst_D0      (<connected-to-hps_io_hps_io_usb1_inst_D0>),      //                    .hps_io_usb1_inst_D0
		.hps_io_hps_io_usb1_inst_D1      (<connected-to-hps_io_hps_io_usb1_inst_D1>),      //                    .hps_io_usb1_inst_D1
		.hps_io_hps_io_usb1_inst_D2      (<connected-to-hps_io_hps_io_usb1_inst_D2>),      //                    .hps_io_usb1_inst_D2
		.hps_io_hps_io_usb1_inst_D3      (<connected-to-hps_io_hps_io_usb1_inst_D3>),      //                    .hps_io_usb1_inst_D3
		.hps_io_hps_io_usb1_inst_D4      (<connected-to-hps_io_hps_io_usb1_inst_D4>),      //                    .hps_io_usb1_inst_D4
		.hps_io_hps_io_usb1_inst_D5      (<connected-to-hps_io_hps_io_usb1_inst_D5>),      //                    .hps_io_usb1_inst_D5
		.hps_io_hps_io_usb1_inst_D6      (<connected-to-hps_io_hps_io_usb1_inst_D6>),      //                    .hps_io_usb1_inst_D6
		.hps_io_hps_io_usb1_inst_D7      (<connected-to-hps_io_hps_io_usb1_inst_D7>),      //                    .hps_io_usb1_inst_D7
		.hps_io_hps_io_usb1_inst_CLK     (<connected-to-hps_io_hps_io_usb1_inst_CLK>),     //                    .hps_io_usb1_inst_CLK
		.hps_io_hps_io_usb1_inst_STP     (<connected-to-hps_io_hps_io_usb1_inst_STP>),     //                    .hps_io_usb1_inst_STP
		.hps_io_hps_io_usb1_inst_DIR     (<connected-to-hps_io_hps_io_usb1_inst_DIR>),     //                    .hps_io_usb1_inst_DIR
		.hps_io_hps_io_usb1_inst_NXT     (<connected-to-hps_io_hps_io_usb1_inst_NXT>),     //                    .hps_io_usb1_inst_NXT
		.hps_io_hps_io_spim1_inst_CLK    (<connected-to-hps_io_hps_io_spim1_inst_CLK>),    //                    .hps_io_spim1_inst_CLK
		.hps_io_hps_io_spim1_inst_MOSI   (<connected-to-hps_io_hps_io_spim1_inst_MOSI>),   //                    .hps_io_spim1_inst_MOSI
		.hps_io_hps_io_spim1_inst_MISO   (<connected-to-hps_io_hps_io_spim1_inst_MISO>),   //                    .hps_io_spim1_inst_MISO
		.hps_io_hps_io_spim1_inst_SS0    (<connected-to-hps_io_hps_io_spim1_inst_SS0>),    //                    .hps_io_spim1_inst_SS0
		.hps_io_hps_io_uart0_inst_RX     (<connected-to-hps_io_hps_io_uart0_inst_RX>),     //                    .hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX     (<connected-to-hps_io_hps_io_uart0_inst_TX>),     //                    .hps_io_uart0_inst_TX
		.hps_io_hps_io_i2c0_inst_SDA     (<connected-to-hps_io_hps_io_i2c0_inst_SDA>),     //                    .hps_io_i2c0_inst_SDA
		.hps_io_hps_io_i2c0_inst_SCL     (<connected-to-hps_io_hps_io_i2c0_inst_SCL>),     //                    .hps_io_i2c0_inst_SCL
		.hps_io_hps_io_i2c1_inst_SDA     (<connected-to-hps_io_hps_io_i2c1_inst_SDA>),     //                    .hps_io_i2c1_inst_SDA
		.hps_io_hps_io_i2c1_inst_SCL     (<connected-to-hps_io_hps_io_i2c1_inst_SCL>),     //                    .hps_io_i2c1_inst_SCL
		.hps_io_hps_io_gpio_inst_GPIO09  (<connected-to-hps_io_hps_io_gpio_inst_GPIO09>),  //                    .hps_io_gpio_inst_GPIO09
		.hps_io_hps_io_gpio_inst_GPIO35  (<connected-to-hps_io_hps_io_gpio_inst_GPIO35>),  //                    .hps_io_gpio_inst_GPIO35
		.hps_io_hps_io_gpio_inst_GPIO53  (<connected-to-hps_io_hps_io_gpio_inst_GPIO53>),  //                    .hps_io_gpio_inst_GPIO53
		.hps_io_hps_io_gpio_inst_GPIO54  (<connected-to-hps_io_hps_io_gpio_inst_GPIO54>),  //                    .hps_io_gpio_inst_GPIO54
		.hps_io_hps_io_gpio_inst_GPIO61  (<connected-to-hps_io_hps_io_gpio_inst_GPIO61>),  //                    .hps_io_gpio_inst_GPIO61
		.memory_mem_a                    (<connected-to-memory_mem_a>),                    //              memory.mem_a
		.memory_mem_ba                   (<connected-to-memory_mem_ba>),                   //                    .mem_ba
		.memory_mem_ck                   (<connected-to-memory_mem_ck>),                   //                    .mem_ck
		.memory_mem_ck_n                 (<connected-to-memory_mem_ck_n>),                 //                    .mem_ck_n
		.memory_mem_cke                  (<connected-to-memory_mem_cke>),                  //                    .mem_cke
		.memory_mem_cs_n                 (<connected-to-memory_mem_cs_n>),                 //                    .mem_cs_n
		.memory_mem_ras_n                (<connected-to-memory_mem_ras_n>),                //                    .mem_ras_n
		.memory_mem_cas_n                (<connected-to-memory_mem_cas_n>),                //                    .mem_cas_n
		.memory_mem_we_n                 (<connected-to-memory_mem_we_n>),                 //                    .mem_we_n
		.memory_mem_reset_n              (<connected-to-memory_mem_reset_n>),              //                    .mem_reset_n
		.memory_mem_dq                   (<connected-to-memory_mem_dq>),                   //                    .mem_dq
		.memory_mem_dqs                  (<connected-to-memory_mem_dqs>),                  //                    .mem_dqs
		.memory_mem_dqs_n                (<connected-to-memory_mem_dqs_n>),                //                    .mem_dqs_n
		.memory_mem_odt                  (<connected-to-memory_mem_odt>),                  //                    .mem_odt
		.memory_mem_dm                   (<connected-to-memory_mem_dm>),                   //                    .mem_dm
		.memory_oct_rzqin                (<connected-to-memory_oct_rzqin>),                //                    .oct_rzqin
		.pll_0_locked_export             (<connected-to-pll_0_locked_export>),             //        pll_0_locked.export
		.pll_0_outclk0_clk               (<connected-to-pll_0_outclk0_clk>),               //       pll_0_outclk0.clk
		.pll_0_outclk1_clk               (<connected-to-pll_0_outclk1_clk>),               //       pll_0_outclk1.clk
		.reset_reset_n                   (<connected-to-reset_reset_n>)                    //               reset.reset_n
	);

